{% set name = "pytest-speed" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e76208eb37362d0de9ce228488d18b5d96b95ea0dec6b0ad0e0f4ddfa359f3b0

build:
  entry_points:
    - pytest-speed = pytest_speed.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - pytest >=7
    - click >=7
    - rich >=12

test:
  imports:
    - pytest_speed
  commands:
    - pip check
    - pytest-speed --help
  requires:
    - pip

about:
  home: https://github.com/samuelcolvin/pytest-speed
  summary: Modern benchmarking library for python with pytest integration.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
